import type { TalentNodeDef } from "./types";

export const TALENT_DEFS: TalentNodeDef[] = [
  {
    id: "core_vitality_training",
    path: "core",
    tier: 0,
    name: "Vitality Training",
    description: "Increase baseline max health.",
    cost: 24,
    maxRank: 1,
    prerequisites: [],
    effects: [{ type: "derived_stat_flat", stat: "maxHealth", value: 10 }],
    uiPosition: { x: 80, y: 40 }
  },
  {
    id: "core_iron_skin",
    path: "core",
    tier: 1,
    name: "Iron Skin",
    description: "Increase baseline armor.",
    cost: 24,
    maxRank: 1,
    prerequisites: [{ talentId: "core_vitality_training", minRank: 1 }],
    effects: [{ type: "derived_stat_flat", stat: "armor", value: 2 }],
    uiPosition: { x: 40, y: 120 }
  },
  {
    id: "core_keen_eye",
    path: "core",
    tier: 1,
    name: "Keen Eye",
    description: "Increase baseline critical chance.",
    cost: 20,
    maxRank: 1,
    prerequisites: [{ talentId: "core_vitality_training", minRank: 1 }],
    effects: [{ type: "derived_stat_percent", stat: "critChance", value: 0.05 }],
    uiPosition: { x: 120, y: 120 }
  },
  {
    id: "warrior_blooded_edge",
    path: "warrior",
    tier: 0,
    name: "Blooded Edge",
    description: "Increase strength.",
    cost: 36,
    maxRank: 1,
    prerequisites: [],
    effects: [{ type: "base_stat_flat", stat: "strength", value: 2 }],
    uiPosition: { x: 40, y: 40 }
  },
  {
    id: "warrior_crushing_weight",
    path: "warrior",
    tier: 1,
    name: "Crushing Weight",
    description: "Increase attack power.",
    cost: 42,
    maxRank: 1,
    prerequisites: [{ talentId: "warrior_blooded_edge", minRank: 1 }],
    effects: [{ type: "derived_stat_flat", stat: "attackPower", value: 8 }],
    uiPosition: { x: 100, y: 80 }
  },
  {
    id: "warrior_brutal_momentum",
    path: "warrior",
    tier: 2,
    name: "Brutal Momentum",
    description: "Increase attack speed.",
    cost: 48,
    maxRank: 1,
    prerequisites: [{ talentId: "warrior_crushing_weight", minRank: 1 }],
    effects: [{ type: "derived_stat_percent", stat: "attackSpeed", value: 0.05 }],
    uiPosition: { x: 40, y: 130 }
  },
  {
    id: "warrior_colossus_frame",
    path: "warrior",
    tier: 3,
    name: "Colossus Frame",
    description: "Increase vitality.",
    cost: 54,
    maxRank: 1,
    prerequisites: [{ talentId: "warrior_brutal_momentum", minRank: 1 }],
    effects: [{ type: "base_stat_flat", stat: "vitality", value: 2 }],
    uiPosition: { x: 100, y: 170 }
  },
  {
    id: "warrior_executioner_instinct",
    path: "warrior",
    tier: 4,
    name: "Executioner Instinct",
    description: "Increase attack power by percent.",
    cost: 60,
    maxRank: 1,
    prerequisites: [{ talentId: "warrior_colossus_frame", minRank: 1 }],
    effects: [{ type: "derived_stat_percent", stat: "attackPower", value: 0.08 }],
    uiPosition: { x: 40, y: 220 }
  },
  {
    id: "warrior_undying_stride",
    path: "warrior",
    tier: 5,
    name: "Undying Stride",
    description: "Increase max health.",
    cost: 66,
    maxRank: 1,
    prerequisites: [{ talentId: "warrior_executioner_instinct", minRank: 1 }],
    effects: [{ type: "derived_stat_flat", stat: "maxHealth", value: 24 }],
    uiPosition: { x: 100, y: 260 }
  },
  {
    id: "ranger_shadow_step",
    path: "ranger",
    tier: 0,
    name: "Shadow Step",
    description: "Increase dexterity.",
    cost: 36,
    maxRank: 1,
    prerequisites: [],
    effects: [{ type: "base_stat_flat", stat: "dexterity", value: 2 }],
    uiPosition: { x: 40, y: 40 }
  },
  {
    id: "ranger_quickdraw",
    path: "ranger",
    tier: 1,
    name: "Quickdraw",
    description: "Increase attack speed.",
    cost: 42,
    maxRank: 1,
    prerequisites: [{ talentId: "ranger_shadow_step", minRank: 1 }],
    effects: [{ type: "derived_stat_percent", stat: "attackSpeed", value: 0.06 }],
    uiPosition: { x: 100, y: 80 }
  },
  {
    id: "ranger_hawk_eye",
    path: "ranger",
    tier: 2,
    name: "Hawk Eye",
    description: "Increase critical chance.",
    cost: 48,
    maxRank: 1,
    prerequisites: [{ talentId: "ranger_quickdraw", minRank: 1 }],
    effects: [{ type: "derived_stat_percent", stat: "critChance", value: 0.03 }],
    uiPosition: { x: 40, y: 130 }
  },
  {
    id: "ranger_windrunner",
    path: "ranger",
    tier: 3,
    name: "Windrunner",
    description: "Increase movement speed.",
    cost: 54,
    maxRank: 1,
    prerequisites: [{ talentId: "ranger_hawk_eye", minRank: 1 }],
    effects: [{ type: "derived_stat_percent", stat: "moveSpeed", value: 0.05 }],
    uiPosition: { x: 100, y: 170 }
  },
  {
    id: "ranger_venom_threads",
    path: "ranger",
    tier: 4,
    name: "Venom Threads",
    description: "Increase attack power.",
    cost: 60,
    maxRank: 1,
    prerequisites: [{ talentId: "ranger_windrunner", minRank: 1 }],
    effects: [{ type: "derived_stat_flat", stat: "attackPower", value: 6 }],
    uiPosition: { x: 40, y: 220 }
  },
  {
    id: "ranger_predator_focus",
    path: "ranger",
    tier: 5,
    name: "Predator Focus",
    description: "Increase dexterity further.",
    cost: 66,
    maxRank: 1,
    prerequisites: [{ talentId: "ranger_venom_threads", minRank: 1 }],
    effects: [{ type: "base_stat_flat", stat: "dexterity", value: 3 }],
    uiPosition: { x: 100, y: 260 }
  },
  {
    id: "arcanist_mindforge",
    path: "arcanist",
    tier: 0,
    name: "Mindforge",
    description: "Increase intelligence.",
    cost: 36,
    maxRank: 1,
    prerequisites: [],
    effects: [{ type: "base_stat_flat", stat: "intelligence", value: 2 }],
    uiPosition: { x: 40, y: 40 }
  },
  {
    id: "arcanist_aether_pool",
    path: "arcanist",
    tier: 1,
    name: "Aether Pool",
    description: "Increase max mana.",
    cost: 42,
    maxRank: 1,
    prerequisites: [{ talentId: "arcanist_mindforge", minRank: 1 }],
    effects: [{ type: "derived_stat_flat", stat: "maxMana", value: 18 }],
    uiPosition: { x: 100, y: 80 }
  },
  {
    id: "arcanist_sigil_acceleration",
    path: "arcanist",
    tier: 2,
    name: "Sigil Acceleration",
    description: "Increase attack speed.",
    cost: 48,
    maxRank: 1,
    prerequisites: [{ talentId: "arcanist_aether_pool", minRank: 1 }],
    effects: [{ type: "derived_stat_percent", stat: "attackSpeed", value: 0.04 }],
    uiPosition: { x: 40, y: 130 }
  },
  {
    id: "arcanist_crystal_focus",
    path: "arcanist",
    tier: 3,
    name: "Crystal Focus",
    description: "Increase attack power.",
    cost: 54,
    maxRank: 1,
    prerequisites: [{ talentId: "arcanist_sigil_acceleration", minRank: 1 }],
    effects: [{ type: "derived_stat_flat", stat: "attackPower", value: 7 }],
    uiPosition: { x: 100, y: 170 }
  },
  {
    id: "arcanist_phase_dodge",
    path: "arcanist",
    tier: 4,
    name: "Phase Dodge",
    description: "Gain phase dodge trigger chance.",
    cost: 60,
    maxRank: 1,
    prerequisites: [{ talentId: "arcanist_crystal_focus", minRank: 1 }],
    effects: [{ type: "trigger", key: "phaseDodge", value: 0.1 }],
    uiPosition: { x: 40, y: 220 }
  },
  {
    id: "arcanist_mana_shield",
    path: "arcanist",
    tier: 5,
    name: "Mana Shield",
    description: "Gain mana shield trigger chance.",
    cost: 66,
    maxRank: 1,
    prerequisites: [{ talentId: "arcanist_phase_dodge", minRank: 1 }],
    effects: [{ type: "trigger", key: "manaShield", value: 0.12 }],
    uiPosition: { x: 100, y: 260 }
  },
  {
    id: "utility_potion_satchel",
    path: "utility",
    tier: 0,
    name: "Potion Satchel",
    description: "Increase potion charge capacity.",
    cost: 25,
    maxRank: 1,
    prerequisites: [],
    effects: [{ type: "capacity", key: "potionCharges", value: 1 }],
    uiPosition: { x: 40, y: 40 }
  },
  {
    id: "utility_skill_slot_i",
    path: "utility",
    tier: 1,
    name: "Third Skill Slot",
    description: "Unlock one additional skill slot.",
    cost: 30,
    maxRank: 1,
    prerequisites: [{ talentId: "utility_potion_satchel", minRank: 1 }],
    effects: [{ type: "capacity", key: "skillSlots", value: 1 }],
    uiPosition: { x: 100, y: 80 }
  },
  {
    id: "utility_skill_slot_ii",
    path: "utility",
    tier: 2,
    name: "Fourth Skill Slot",
    description: "Unlock one additional skill slot.",
    cost: 35,
    maxRank: 1,
    prerequisites: [{ talentId: "utility_skill_slot_i", minRank: 1 }],
    effects: [{ type: "capacity", key: "skillSlots", value: 1 }],
    uiPosition: { x: 40, y: 130 }
  },
  {
    id: "utility_merchant_sense",
    path: "utility",
    tier: 3,
    name: "Merchant Sense",
    description: "Gain merchant discount in run.",
    cost: 40,
    maxRank: 1,
    prerequisites: [{ talentId: "utility_skill_slot_ii", minRank: 1 }],
    effects: [{ type: "economy", key: "merchantDiscount", value: 0.08 }],
    uiPosition: { x: 100, y: 170 }
  },
  {
    id: "utility_death_ledger",
    path: "utility",
    tier: 4,
    name: "Death Ledger",
    description: "Retain more shards on failure.",
    cost: 45,
    maxRank: 1,
    prerequisites: [{ talentId: "utility_merchant_sense", minRank: 1 }],
    effects: [{ type: "economy", key: "deathRetention", value: 0.1 }],
    uiPosition: { x: 40, y: 220 }
  },
  {
    id: "utility_lethal_guard",
    path: "utility",
    tier: 5,
    name: "Lethal Guard",
    description: "Gain lethal guard trigger chance.",
    cost: 50,
    maxRank: 1,
    prerequisites: [{ talentId: "utility_death_ledger", minRank: 1 }],
    effects: [{ type: "trigger", key: "lethalGuard", value: 0.1 }],
    uiPosition: { x: 100, y: 260 }
  }
];

export const TALENT_DEF_MAP = Object.fromEntries(TALENT_DEFS.map((entry) => [entry.id, entry])) as Record<
  TalentNodeDef["id"],
  TalentNodeDef
>;
