import Phaser from "phaser";
export declare class DungeonScene extends Phaser.Scene {
    private static readonly ENTITY_DEPTH_OFFSET;
    private readonly entityManager;
    private readonly movementSystem;
    private readonly aiSystem;
    private readonly combatSystem;
    private readonly monsterSpawnSystem;
    private readonly eventBus;
    private readonly renderSystem;
    private hud;
    private meta;
    private run;
    private runSeed;
    private spawnRng;
    private combatRng;
    private lootRng;
    private dungeon;
    private player;
    private playerSprite;
    private path;
    private attackTargetId;
    private origin;
    private worldBounds;
    private readonly tileWidth;
    private readonly tileHeight;
    private playerYOffset;
    private nextPlayerAttackAt;
    private hudDirty;
    private runEnded;
    constructor();
    preload(): void;
    create(): void;
    update(_: number, deltaMs: number): void;
    private bindDomainEventEffects;
    private resolveInitialRunSeed;
    private bootstrapRun;
    private configureRngStreams;
    private makeInitialPlayer;
    private handlePointerDown;
    private updatePlayerMovement;
    private updateCombat;
    private emitCombatEvents;
    private updateMonsters;
    private updateMonsterCombat;
    private collectNearbyLoot;
    private computePathTo;
    private spawnMonsters;
    private spawnLootDrop;
    private finishRun;
    private resetRun;
    private renderHud;
    private cleanupScene;
    private loadMeta;
    private saveMeta;
}
//# sourceMappingURL=DungeonScene.d.ts.map